### ISSUE TITLE
fail2ban using iptables-legacy instead of iptables

### ISSUE THREAD

**Issue by psidex** [crazy-max/docker-fail2ban#66]
### Behaviour

In [this comment](https://github.com/crazy-max/docker-fail2ban/issues/56#issuecomment-666740573), it is mentioned that you can use `iptables -S | grep f2b` to see the banned IPs in iptables, when I try to do that I get this:

```bash
~$ sudo iptables -S | grep f2b
# Warning: iptables-legacy tables present, use iptables-legacy to see them
~$ sudo iptables-legacy -S | grep f2b
-A f2b-sshd -s 1.11.201.18/32 -j REJECT --reject-with icmp-port-unreachable
-A f2b-sshd -s 1.10.133.55/32 -j REJECT --reject-with icmp-port-unreachable
-A f2b-sshd -s 1.1.186.208/32 -j REJECT --reject-with icmp-port-unreachable
etc.
```

#### Steps to reproduce this issue

1. Follow the docs at the [sshd example](https://github.com/crazy-max/docker-fail2ban/tree/master/examples/jails/sshd)

### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.12, build 48a66213fe
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian GNU/Linux 10 (buster)
* System info (type `uname -a`) : Linux apollo 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux

### Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 77
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-8-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.902GiB
 Name: apollo
 ID: CQKT:FWY5:L44P:4CX5:CEER:W6SM:YKZT:FPD7:VNHL:3D4V:BARG:MKYB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Logs

[gist](https://gist.github.com/psidex/db37489993713caab61d6fa915d1d715#file-docker-logs-fail2ban)

**Comment by 42aroger** [comment]
You can run on your host : 

update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

iptables as been changed to iptables-legacy since debian 10

In my case the rules in iptables are not working. Reject IPs still can connect.
Any help would be appreciate

**Comment by hlugt** [comment]
Old but since I also ran into this, and my nas does not use nftables or can replace the used iptables:
You are aware that you can change the behaviour/settings?

edit /etc/fail2ban/action.d/iptables-common.conf (or copy it to /data/action.d to let it overrule)
comment the line
#blocktype = REJECT --reject-with icmp-port-unreachable
and replace with
blocktype = DROP
