### ISSUE TITLE
User namespace known limitation

### ISSUE THREAD

**Issue by CaosFR** [crazy-max/docker-fail2ban#96]
I have a problem when I try to implement CIS Security feature.

If I implement this security :

$ nano /etc/daemon.json
{
"userns-remap": "default",
}

I get this error on stratup :
ERROR: for fail2ban Cannot create container for service fail2ban: cannot share the host's network namespace when user namespaces are enabled

According to the Docker documentation (https://docs.docker.com/engine/security/userns-remap/) this error is bind to this param : --network=host

I have see a other repport for this problem but it's closed without answer.
Does a way to solve it ?

TY

**Comment by cybermcm** [comment]
Just a hint, never tried it myself:
https://docs.docker.com/engine/security/rootless/
Seems the way to go in terms of security, although there are also [limitations](https://docs.docker.com/engine/security/rootless/#known-limitations).

Probably not working since F2B has to alter FW rules from host to work like expected...
